//! Rust-side SQLite for the Sidebar — allows the Tauri desktop app to read/write
//! the local ASE + workflow database without depending on the Python backend.
//!
//! The schema is fully compatible with the Python FastAPI backend so that both
//! can operate on the same `catgo_results.db` file.

pub mod files;
pub mod results;
pub mod util;
pub mod workflow;

use rusqlite::Connection;
use std::path::PathBuf;
use std::sync::Mutex;

// Sub-modules are `pub` so that `lib.rs` can reference `db::workflow::db_list_projects` etc.
// in the `generate_handler!` macro (which needs the actual module path for the hidden
// `__cmd__` symbols generated by `#[tauri::command]`).

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

pub struct DbState {
    /// Currently active DB path. `None` -> use default.
    active_path: Mutex<Option<String>>,
}

impl Default for DbState {
    fn default() -> Self {
        Self {
            active_path: Mutex::new(None),
        }
    }
}

impl DbState {
    /// Resolve the active DB path as a String (for use by other modules).
    pub fn resolve_path(&self) -> Result<String, String> {
        let guard = self.active_path.lock().map_err(|e| e.to_string())?;
        let path = match guard.as_deref() {
            Some(p) => PathBuf::from(p),
            None => resolve_default_path(),
        };
        Ok(path.to_string_lossy().to_string())
    }
}

/// Resolve the active DB path (or fall back to `server/data/catgo_results.db`
/// relative to the project root).
///
/// IMPORTANT: `tauri dev` runs `cargo run` with CWD = `src-tauri/`, so bare
/// relative paths like `server/data/...` resolve INSIDE `src-tauri/` and create
/// files that trigger the Tauri file-watcher -> infinite rebuild loop -> crash.
/// We detect the project root by walking up from CWD to find `package.json`.
fn resolve_default_path() -> PathBuf {
    let home = std::env::var("HOME").or_else(|_| std::env::var("USERPROFILE")).unwrap_or_else(|_| ".".to_string());
    let base_dir = PathBuf::from(home).join(".catgo");
    
    // Ensure .catgo directory exists
    if !base_dir.exists() {
        let _ = std::fs::create_dir_all(&base_dir);
    }
    
    base_dir.join("catgo_results.db")
}

pub(crate) fn get_conn(state: &DbState) -> Result<Connection, String> {
    let path = {
        let guard = state.active_path.lock().map_err(|e| e.to_string())?;
        match guard.as_deref() {
            Some(p) => PathBuf::from(p),
            None => resolve_default_path(),
        }
    };
    // Ensure parent dir exists
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("mkdir: {e}"))?;
    }
    let conn = Connection::open(&path).map_err(|e| format!("sqlite open: {e}"))?;
    conn.execute_batch(
        "PRAGMA journal_mode=WAL;
         PRAGMA foreign_keys=ON;
         PRAGMA busy_timeout=5000;",
    )
    .map_err(|e| format!("pragma: {e}"))?;
    ensure_tables(&conn)?;
    Ok(conn)
}

// ---------------------------------------------------------------------------
// Table creation (compatible with Python backend)
// ---------------------------------------------------------------------------

fn ensure_tables(conn: &Connection) -> Result<(), String> {
    conn.execute_batch(
        "
        -- Workflow tables
        CREATE TABLE IF NOT EXISTS projects (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT DEFAULT '',
            ase_db_path TEXT,
            parent_id TEXT REFERENCES projects(id),
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS workflows (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT DEFAULT '',
            template_id TEXT,
            status TEXT DEFAULT 'draft',
            graph_json TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            metadata TEXT DEFAULT '{}',
            project_id TEXT REFERENCES projects(id),
            run_config_json TEXT DEFAULT '{}'
        );
        CREATE TABLE IF NOT EXISTS workflow_steps (
            id TEXT PRIMARY KEY,
            workflow_id TEXT NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
            node_type TEXT NOT NULL,
            label TEXT DEFAULT '',
            config_json TEXT DEFAULT '{}',
            status TEXT DEFAULT 'pending',
            hpc_job_id TEXT,
            hpc_session_id TEXT,
            ase_db_id INTEGER,
            input_ase_db_id INTEGER,
            result_json TEXT DEFAULT '{}',
            error_message TEXT,
            started_at TEXT,
            completed_at TEXT,
            work_dir TEXT,
            input_source TEXT
        );
        CREATE TABLE IF NOT EXISTS workflow_edges (
            id TEXT PRIMARY KEY,
            workflow_id TEXT NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
            source_step_id TEXT NOT NULL,
            target_step_id TEXT NOT NULL,
            edge_type TEXT DEFAULT 'sequential',
            condition_json TEXT DEFAULT '{}',
            source_handle TEXT,
            target_handle TEXT
        );
        CREATE TABLE IF NOT EXISTS workflow_templates (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT DEFAULT '',
            category TEXT DEFAULT 'general',
            graph_json TEXT NOT NULL,
            metadata TEXT DEFAULT '{}'
        );
        CREATE TABLE IF NOT EXISTS workflow_folders (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT DEFAULT '',
            parent_id TEXT REFERENCES workflow_folders(id),
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_steps_workflow ON workflow_steps(workflow_id);
        CREATE INDEX IF NOT EXISTS idx_steps_status ON workflow_steps(status);
        CREATE INDEX IF NOT EXISTS idx_edges_workflow ON workflow_edges(workflow_id);

        -- ASE tables
        CREATE TABLE IF NOT EXISTS systems (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            unique_id TEXT UNIQUE,
            ctime REAL,
            mtime REAL,
            username TEXT,
            numbers BLOB,
            positions BLOB,
            cell BLOB,
            pbc INTEGER,
            initial_magmoms BLOB,
            initial_charges BLOB,
            masses BLOB,
            tags BLOB,
            momenta BLOB,
            constraints TEXT,
            calculator TEXT,
            calculator_parameters TEXT,
            energy REAL,
            free_energy REAL,
            forces BLOB,
            stress BLOB,
            dipole BLOB,
            magmoms BLOB,
            magmom REAL,
            charges BLOB,
            key_value_pairs TEXT,
            data BLOB,
            natoms INTEGER,
            fmax REAL,
            smax REAL,
            volume REAL,
            mass REAL,
            charge REAL
        );
        CREATE TABLE IF NOT EXISTS species (
            Z INTEGER,
            n INTEGER,
            id INTEGER,
            FOREIGN KEY (id) REFERENCES systems(id)
        );
        CREATE TABLE IF NOT EXISTS keys (
            key TEXT,
            id INTEGER,
            FOREIGN KEY (id) REFERENCES systems(id)
        );
        CREATE TABLE IF NOT EXISTS text_key_values (
            key TEXT,
            value TEXT,
            id INTEGER,
            FOREIGN KEY (id) REFERENCES systems(id)
        );
        CREATE TABLE IF NOT EXISTS number_key_values (
            key TEXT,
            value REAL,
            id INTEGER,
            FOREIGN KEY (id) REFERENCES systems(id)
        );
        CREATE TABLE IF NOT EXISTS information (
            name TEXT,
            value TEXT
        );
        CREATE INDEX IF NOT EXISTS unique_id_index ON systems(unique_id);
        CREATE INDEX IF NOT EXISTS ctime_index ON systems(ctime);
        CREATE INDEX IF NOT EXISTS username_index ON systems(username);
        CREATE INDEX IF NOT EXISTS calculator_index ON systems(calculator);
        CREATE INDEX IF NOT EXISTS species_index ON species(Z);
        CREATE INDEX IF NOT EXISTS key_index ON keys(key);
        CREATE INDEX IF NOT EXISTS text_index ON text_key_values(key);
        CREATE INDEX IF NOT EXISTS number_index ON number_key_values(key);
        ",
    )
    .map_err(|e| format!("ensure_tables: {e}"))?;

    // Insert ASE version marker if not present
    let count: i64 = conn
        .query_row("SELECT COUNT(*) FROM information", [], |r| r.get(0))
        .unwrap_or(0);
    if count == 0 {
        conn.execute(
            "INSERT INTO information (name, value) VALUES ('version', '9')",
            [],
        )
        .ok();
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Serde types for DB management JSON output
// ---------------------------------------------------------------------------

#[derive(serde::Serialize)]
pub struct DbInfo {
    path: String,
    name: String,
}

// ---------------------------------------------------------------------------
// Tauri commands: DB management
// ---------------------------------------------------------------------------

#[tauri::command]
pub fn db_get_current(state: tauri::State<'_, DbState>) -> Result<DbInfo, String> {
    let guard = state.active_path.lock().map_err(|e| e.to_string())?;
    let path = match guard.as_deref() {
        Some(p) => PathBuf::from(p),
        None => resolve_default_path(),
    };
    let name = path
        .file_stem()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_default();
    Ok(DbInfo {
        path: path.to_string_lossy().to_string(),
        name,
    })
}

#[tauri::command]
pub fn db_new(state: tauri::State<'_, DbState>, path: String) -> Result<DbInfo, String> {
    let mut p = PathBuf::from(&path);
    if p.extension().is_none() {
        p.set_extension("db");
    }
    if let Some(parent) = p.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("mkdir: {e}"))?;
    }
    // Remove existing file (user chose to overwrite)
    if p.exists() {
        std::fs::remove_file(&p).map_err(|e| format!("remove: {e}"))?;
    }
    // Create and initialize
    let conn = Connection::open(&p).map_err(|e| format!("sqlite: {e}"))?;
    conn.execute_batch("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;")
        .map_err(|e| format!("pragma: {e}"))?;
    ensure_tables(&conn).map_err(|e| format!("tables: {e}"))?;
    drop(conn);

    // Switch active
    let mut guard = state.active_path.lock().map_err(|e| e.to_string())?;
    *guard = Some(p.to_string_lossy().to_string());

    let name = p.file_stem().map(|s| s.to_string_lossy().to_string()).unwrap_or_default();
    Ok(DbInfo {
        path: p.to_string_lossy().to_string(),
        name,
    })
}

#[tauri::command]
pub fn db_open(state: tauri::State<'_, DbState>, path: String) -> Result<DbInfo, String> {
    let p = PathBuf::from(&path);
    if !p.exists() {
        return Err(format!("File not found: {path}"));
    }
    // Open and ensure workflow tables exist (they might be missing in pure ASE DBs)
    let conn = Connection::open(&p).map_err(|e| format!("sqlite: {e}"))?;
    conn.execute_batch("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;")
        .map_err(|e| format!("pragma: {e}"))?;
    ensure_tables(&conn).map_err(|e| format!("tables: {e}"))?;
    drop(conn);

    let mut guard = state.active_path.lock().map_err(|e| e.to_string())?;
    *guard = Some(p.to_string_lossy().to_string());

    let name = p.file_stem().map(|s| s.to_string_lossy().to_string()).unwrap_or_default();
    Ok(DbInfo {
        path: p.to_string_lossy().to_string(),
        name,
    })
}

#[tauri::command]
pub fn db_save_as(state: tauri::State<'_, DbState>, path: String) -> Result<DbInfo, String> {
    let src = {
        let guard = state.active_path.lock().map_err(|e| e.to_string())?;
        match guard.as_deref() {
            Some(p) => PathBuf::from(p),
            None => resolve_default_path(),
        }
    };
    let mut dst = PathBuf::from(&path);
    if dst.extension().is_none() {
        dst.set_extension("db");
    }
    if let Some(parent) = dst.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("mkdir: {e}"))?;
    }
    if src.exists() {
        std::fs::copy(&src, &dst).map_err(|e| format!("copy: {e}"))?;
    } else {
        // Source doesn't exist — create empty
        let conn = Connection::open(&dst).map_err(|e| format!("sqlite: {e}"))?;
        conn.execute_batch("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;")
            .map_err(|e| format!("pragma: {e}"))?;
        ensure_tables(&conn)?;
    }

    let mut guard = state.active_path.lock().map_err(|e| e.to_string())?;
    *guard = Some(dst.to_string_lossy().to_string());

    let name = dst.file_stem().map(|s| s.to_string_lossy().to_string()).unwrap_or_default();
    Ok(DbInfo {
        path: dst.to_string_lossy().to_string(),
        name,
    })
}
