// The three JS-invokable commands. tauri_plugin::Builder autogenerates an
// `allow-<command>` / `deny-<command>` permission for each into
// permissions/autogenerated/, which the app's capability then grants.
// Our own commands, PLUS the two listener commands the iOS Plugin base class
// provides natively (Plugin.swift) and that `addPluginListener` invokes under
// the hood. They have no Rust handlers — listing them here only autogenerates
// their `allow-*` permissions so the ACL stops rejecting them ("registerListener
// not allowed"). Without these, the `partial`/`final` event stream is blocked.
const COMMANDS: &[&str] = &[
    "request_permission",
    "supported_locales",
    "start_listening",
    "stop_listening",
    "register_listener",
    "remove_listener",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .ios_path("ios")
        .build();
}
